"use client";

import { useActionState, useEffect, useRef, useState } from "react";
import { useFormStatus } from "react-dom";
import Image from "next/image";
import Link from "next/link";

import { insertGame } from "../_lib/actions";
import { groupByPlatformOwner } from "../_lib/utils";
import {
  MAXIMUM_IMAGE_SIZE,
  SEALED_COLLECTOR_TEXT,
  SEALED_TEXT,
} from "../_lib/constants";
import InfoRegion from "./InfoRegion";
import PlatformSelector from "./PlatformSelector";
import placeholderImage from "@/public/placeholder-font-80-1000x1000.jpg";
import ContentDescriptionInsert from "./ContentDescriptionInsert";
import { PencilIcon, PlusIcon } from "@heroicons/react/24/solid";
import {
  ArrowTopRightOnSquareIcon,
  QuestionMarkCircleIcon,
} from "@heroicons/react/24/outline";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";

function InsertGameForm({ platforms, platformsIdAndName }) {
  const [curActive, setCurActive] = useState();
  const [titleLength, setTitleLength] = useState(0);
  const [title, setTitle] = useState("");
  const [isSealedChecked, setSealedChecked] = useState(false);
  const [isCollectorChecked, setCollectorChecked] = useState(false);
  const [descriptionValue, setDescriptionValue] = useState("");
  const [notesValue, setNotesValue] = useState("");
  const [listView, setListView] = useState(false);
  const [isOpenInfo, setIsOpenInfo] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [selectedImage, setSelectedImage] = useState(null); // state per anteprima visiva immagine selezionata (url)
  const [imageSize, setImageSize] = useState(undefined); // state che legge dimensioni immagine selezionata
  const hiddenInputRef = useRef(null);
  const router = useRouter();
  const [isConverting, setIsConverting] = useState(false);

  const platformsByOwner = groupByPlatformOwner(platforms, "platformOwner");

  const launchboxDbUrl = `https://gamesdb.launchbox-app.com/games/results/${encodeURIComponent(title)}`;
  const googleImagesUrl = `https://www.google.com/search?tbm=isch&tbs=isz:m&q=${encodeURIComponent(title)}+boxart`;

  // Server action submit + dati extra
  const insertGameWithData = insertGame.bind(null, platformsIdAndName);

  const [state, formAction, isPending] = useActionState(
    insertGameWithData,
    null,
  );

  // Resetta i controlled inputs dopo il submit e fa il redirect in home
  useEffect(() => {
    if (state?.success) {
      setSelectedImage(null);
      setTitleLength(0);
      setDescriptionValue("");
      router.push(state.redirectTo);
    }

    if (state?.error) {
      toast.error(state.message);
      setSelectedImage(null);
      setTitleLength(0);
      setDescriptionValue("");
    }
  }, [state]);

  // Gestione del testo automatico per gioco sigillato
  useEffect(() => {
    let autoText = "";

    if (isSealedChecked && isCollectorChecked) {
      autoText = SEALED_COLLECTOR_TEXT;
    } else if (isSealedChecked) {
      autoText = SEALED_TEXT;
    }

    // scrive solo se NON è stato toccato dall’utente
    if (!descriptionValue || isAutoGenerated) {
      setDescriptionValue(autoText);
      setIsAutoGenerated(true);
    }
  }, [isSealedChecked, isCollectorChecked]);

  function handleRegionInfo(e) {
    e.preventDefault();
    setIsOpenInfo(true);
  }

  async function handleChangeImage(e) {
    const file = e.target?.files[0];

    // Due variabili per lo state che legge le dimensioni del file
    let fileSizeInBytes; // dimensione file in bytes
    let formattedFileSize; // dimensione file formattata (MB o KB)
    const KB = 1000;
    const MB = 1000 * 1000;

    // Se c'è un file selezionato dall'utente
    if (file) {
      fileSizeInBytes = file.size;

      // se l'immagine è >1MB formatta la stringa in MB (es. "1.5MB")
      if (fileSizeInBytes >= MB) {
        formattedFileSize = (fileSizeInBytes / MB).toFixed(2) + " MB";
        // se l'immagine è <1MB formatta la stringa in KB (es. "378KB")
      } else {
        formattedFileSize = Math.round(fileSizeInBytes / KB) + " KB";
      }

      // Se l'immagine è già webp e non supera la dimensione massima consentita,
      // la mette subito nell'input hidden per mandarla alla server action
      if (file.size <= MAXIMUM_IMAGE_SIZE) {
        setImageSize({
          formattedSize: formattedFileSize,
          rawSize: fileSizeInBytes,
        });
        // Inserisce il file direttamente nel file input nascosto tramite DataTransfer
        const dataTransfer = new DataTransfer();
        dataTransfer.items.add(file);
        hiddenInputRef.current.files = dataTransfer.files;
        // Aggiorna lo state dell'immagine selezionata (anteprima)
        setSelectedImage(file ? URL.createObjectURL(file) : placeholderImage);
        return;
      }
    }

    // Se non c'è immagine selezionata resetta
    if (!formattedFileSize) {
      setImageSize(undefined);
      setSelectedImage(null);
    } else {
      // Se c'è immagine selezionata
      // Se supera la grandezza consentita prova a convertirla in webp
      if (fileSizeInBytes > MAXIMUM_IMAGE_SIZE) {
        setIsConverting(true);
        // se è già webp non fa niente
        if (file.type === "images/webp") {
          setSelectedImage(null);
          setImageSize({
            formattedSize: formattedFileSize,
            rawSize: fileSizeInBytes,
          });
          return;
        }

        // Crea un'immagine dal file
        const img = new window.Image();
        img.src = URL.createObjectURL(file);
        await img.decode();

        // Crea il canvas e disegna l'immagine
        const canvas = document.createElement("canvas");
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext("2d");
        ctx.drawImage(img, 0, 0);

        // Funzione per ottenere Blob con fallback
        async function canvasToBlobWithFallback(canvas) {
          return new Promise((resolve) => {
            canvas.toBlob(
              (blob) => {
                if (blob) {
                  resolve({ blob, type: "image/webp", ext: "webp" });
                  setIsConverting(false);
                } else {
                  // se il browser non supporta canvas.toBlob risolve blob null
                  resolve({ blob: null, type: null, ext: null });
                  setIsConverting(false);
                }
              },
              "image/webp",
              0.8,
            );
          });
        }

        // Ottiene il blob (webp)
        const { blob, type, ext } = await canvasToBlobWithFallback(canvas);

        // Se il blob è null, resetta anteprima immagine e mostra dimensioni immagine
        // (per renderizzare avviso immagine troppo grande)
        if (!blob) {
          setSelectedImage(null);
          setImageSize({
            formattedSize: formattedFileSize,
            rawSize: fileSizeInBytes,
          });
          return;
        }

        // Crea un nuovo File con il nome corretto e l'estensione webp
        const newFile = new File(
          [blob],
          file.name.replace(/\.\w+$/, `.${ext}`),
          {
            type,
          },
        );

        // Se l'immagine POST CONVERSIONE NON supera la grandezza consentita
        if (newFile.size <= MAXIMUM_IMAGE_SIZE) {
          setImageSize({
            formattedSize: `${newFile.size >= MB ? (newFile.size / MB).toFixed(2) + " MB" : Math.round(newFile.size / KB) + " KB"}`,
            rawSize: newFile.size,
          });
          // Aggiorna lo state dell'immagine selezionata (anteprima)
          setSelectedImage(file ? URL.createObjectURL(file) : placeholderImage);

          // Inserisce il file convertito nel file input nascosto tramite DataTransfer
          const dataTransfer = new DataTransfer();
          dataTransfer.items.add(newFile);
          hiddenInputRef.current.files = dataTransfer.files;
        } else {
          // Se l'immagine POST CONVERSIONE supera la grandezza consentita
          setImageSize({
            formattedSize: `${newFile.size >= MB ? (newFile.size / MB).toFixed(2) + " MB" : Math.round(newFile.size / KB) + " KB"}`,
            rawSize: newFile.size,
          });
          setSelectedImage(null);
        }
      }
    }
  }

  return (
    <div className="container">
      <form action={formAction}>
        <div className="mb-5 flex flex-col justify-items-start gap-4 py-5 text-lg">
          <h1 className="mb-4 text-center text-2xl">Crea un nuovo gioco</h1>

          {/* IMMAGINE */}
          <div className="mt-4">
            <div
              className={`relative m-auto flex aspect-square max-w-60 flex-col items-center justify-center gap-2 ${selectedImage === null || selectedImage === placeholderImage ? "border-primary rounded border border-dashed" : ""}`}
            >
              <label
                className={`flex h-10 w-10 cursor-pointer items-center justify-center text-2xl ${selectedImage === null || selectedImage === placeholderImage ? "h-full w-full rounded border-0" : "bg-accent absolute right-2 bottom-2 z-50 rounded"}`}
                htmlFor="imageInput"
              >
                {selectedImage === null ||
                selectedImage === placeholderImage ? (
                  <PlusIcon className="h-10 w-10 text-slate-500" />
                ) : (
                  <PencilIcon className="h-5 w-5" />
                )}
              </label>

              {/* Testo box immagine */}
              {selectedImage === null || selectedImage === placeholderImage ? (
                <p
                  className={`absolute top-[60%] text-base ${imageSize?.rawSize > MAXIMUM_IMAGE_SIZE ? "text-amber-400" : "text-slate-500"}`}
                >
                  {isConverting && "Conversione immagine..."}
                  {!isConverting &&
                    `${imageSize?.rawSize > MAXIMUM_IMAGE_SIZE ? `File troppo grande (${imageSize.formattedSize})` : `Scegli Immagine (max 500KB)`}`}
                </p>
              ) : (
                <Image
                  priority
                  alt="Titolo gioco"
                  src={
                    selectedImage !== null ? selectedImage : placeholderImage
                  }
                  fill
                  className="object-cover"
                />
              )}
              <input
                required
                id="imageInput"
                type="file"
                accept=".png,.jpg,.jpeg,.webp,.heic,.heif"
                className="absolute bottom-0 w-full opacity-0 file:hidden"
                onChange={(e) => handleChangeImage(e)}
              />
            </div>
          </div>

          {/* input file nascosto che contiene il WebP pronto per la server action */}
          <input ref={hiddenInputRef} type="file" name="gameImages" hidden />

          {/* Cerca immagine */}
          {titleLength > 0 && (
            <div className="flex flex-col gap-0.5">
              <div className="flex items-center justify-center gap-1 text-sm text-slate-400">
                <span>Cerca immagine su</span>
                <a
                  className="decoration underline decoration-slate-500 underline-offset-2"
                  href={launchboxDbUrl}
                  target="_blank"
                >
                  LaunchBox
                </a>
                <ArrowTopRightOnSquareIcon className="h-2.5 w-2.5" />
              </div>
              <div className="flex items-center justify-center gap-1 text-sm text-slate-400">
                <span>Cerca immagine su</span>
                <a
                  className="decoration underline decoration-slate-500 underline-offset-2"
                  href={googleImagesUrl}
                  target="_blank"
                >
                  Google
                </a>
                <ArrowTopRightOnSquareIcon className="h-2.5 w-2.5" />
              </div>
            </div>
          )}

          {/* TITOLO */}
          <div className="flex flex-col gap-1">
            <div className="flex items-baseline justify-between">
              <label className="text-primary" htmlFor="gameName">
                Titolo
              </label>
              <span className="text-primary text-sm">{titleLength}/100</span>
            </div>
            <input
              autoCapitalize="sentences"
              name="gameName"
              id="gameName"
              type="text"
              className="focus-within:bg-background focus:bg-background focus-within:border-accent focus:ring-accent rounded border border-slate-700 bg-slate-900 p-1.5 text-base focus:ring-1 focus:outline-none"
              autoComplete="off"
              maxLength="100"
              required
              onChange={(e) => {
                setTitle(e.target.value);
                setTitleLength(e.target.value.length);
              }}
            />
          </div>

          {/* REGIONE */}
          <div className="flex flex-col gap-1">
            <div className="flex items-center justify-between">
              <label className="text-primary" htmlFor="gameRegion">
                Regione
              </label>

              <button
                aria-label="Informazioni sulle regioni"
                onClick={(e) => handleRegionInfo(e)}
              >
                <QuestionMarkCircleIcon className="text-primary h-4 w-4" />
              </button>

              {isOpenInfo && <InfoRegion onOpenClose={setIsOpenInfo} />}
            </div>

            <select
              required
              name="gameRegion"
              id="gameRegion"
              className="focus:border-accent focus:ring-accent rounded border border-slate-800 bg-slate-900 p-1 text-base last:border focus-visible:outline-0"
            >
              <option hidden></option>
              <option value="ITA">ITA</option>
              <option value="PAL-ITA">PAL-ITA</option>
              <option value="PAL">PAL</option>
              <option value="NTSC-U">NTSC-U</option>
              <option value="NTSC-J">NTSC-J</option>
            </select>
          </div>

          {/* SIGILLATO */}
          <div className="group text-primary mt-2.5 flex flex-row-reverse items-center justify-end gap-2">
            <label
              htmlFor="isSealed"
              className="group-has-[input:checked]:text-foreground"
            >
              Sigillato
            </label>
            <input
              id="isSealed"
              name="isSealed"
              type="checkbox"
              className="group/checkbox accent-accent h-4 w-4"
              onChange={() => {
                setSealedChecked((isChecked) => !isChecked);
              }}
            />
          </div>

          {/* EDIZIONE SPECIALE */}
          <div className="group text-primary mt-2.5 flex flex-row-reverse items-center justify-end gap-2">
            <label
              htmlFor="isSpecial"
              className="group-has-[input:checked]:text-foreground"
            >
              Edizione speciale (Steelbook, Deluxe ecc.)
            </label>
            <input
              id="isSpecial"
              name="isSpecial"
              type="checkbox"
              className="group/checkbox accent-accent h-4 w-4"
            />
          </div>

          {/* COLLECTOR'S EDITION */}
          <div className="group text-primary mt-2.5 flex flex-row-reverse items-center justify-end gap-2">
            <label
              htmlFor="isCollector"
              className="group-has-[input:checked]:text-foreground"
            >
              Collector's Edition
            </label>
            <input
              id="isCollector"
              name="isCollector"
              type="checkbox"
              className="group/checkbox accent-accent h-4 w-4"
              onChange={() => {
                setCollectorChecked((isChecked) => !isChecked);
              }}
            />
          </div>

          {/* CONTENUTO */}
          <ContentDescriptionInsert
            onAutoGenerated={setIsAutoGenerated}
            descriptionValue={descriptionValue}
            onDescriptionValue={setDescriptionValue}
            listView={listView}
            onListView={setListView}
          />

          {/* NOTE */}
          <div className="mt-1.5 flex flex-col gap-1">
            <div className="flex items-center justify-between">
              <label className="text-primary text-lg" htmlFor="gameNotes">
                Note
              </label>

              <span className="text-primary just text-sm">
                {notesValue.length}/300
              </span>
            </div>
            <textarea
              autoCapitalize="sentences"
              name="gameNotes"
              id="gameNotes"
              className="focus-within:bg-background focus:bg-background placeholder:text-primary/50 focus-within:border-accent focus:ring-accent max-h-44 min-h-20 rounded border border-slate-700 bg-slate-900 p-1.5 text-base focus:placeholder-transparent focus:ring-1 focus:outline-none"
              maxLength="300"
              onChange={(e) => {
                setNotesValue(e.target.value);
              }}
            ></textarea>
          </div>

          {/* PIATTAFORMA */}
          {platforms.length !== 0 ? (
            <div>
              <p className="text-primary mt-3">Piattaforma</p>
              {platformsByOwner.map((platform, i) => (
                <PlatformSelector
                  platformDetails={platform}
                  key={platform[0]}
                  id={i}
                  curActive={curActive}
                  onActive={setCurActive}
                />
              ))}
            </div>
          ) : (
            <>
              <p className="text-primary mt-3">Piattaforme</p>
              <p className="text-primary">
                Non ci sono ancora piattaforme, prima di aggiungere un gioco
                devi{" "}
                <Link
                  className="text-accent decoration-accent underline underline-offset-2"
                  href="/settings/my-platforms"
                >
                  aggiungere una piattaforma
                </Link>
              </p>
            </>
          )}

          {platformsIdAndName.length > 0 && (
            <div className="mt-5 flex items-center justify-center gap-1">
              <Button onListView={setListView} imageSize={imageSize}>
                Crea gioco
              </Button>
            </div>
          )}
        </div>
      </form>
    </div>
  );
}

function Button({ onListView, imageSize }) {
  const { pending } = useFormStatus();

  return (
    <button
      onClick={() => {
        onListView(false);
      }}
      disabled={imageSize?.rawSize > MAXIMUM_IMAGE_SIZE || pending}
      className={`text-foreground mt-5 flex w-full items-center justify-center gap-1 ${pending ? "text-primary animate-pulse" : "border-accent rounded border-2"} px-5 py-1`}
    >
      <span className={`${pending ? "dots-loader animate-pulse" : ""}`}>
        {pending ? "Creazione gioco" : "Crea gioco"}
      </span>
    </button>
  );
}

export default InsertGameForm;
